global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: 'rabbitmq'
    scrape_interval: 5s
    static_configs:
      - targets: ['k8s-rabbitmq:30400']
  
  - job_name: 'redis_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['aliyun-redis:9121','10.64.4.156:9122']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.64.4.167:9100']
        labels:
          hostname: 'k8snode01[10.64.4.167]'
      

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
      
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: "Prod_RDS"
    scrape_interval: 10s
    static_configs:
      - targets: ['prod-rds:9104']

  - job_name: "Prod_RDS_RO"
    scrape_interval: 10s
    static_configs:
      - targets: ['prod-rds-rodida:9105']
  
  - job_name: mongodb-exproter
    scrape_interval: 10s
    static_configs:
      - targets: ['aliyun-mongodb:9104','mongo-on-dockerjack:9104']


  
 
  - job_name: kuaiche_web_status
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['http://www.kuaiche100.cn']
        labels:
          instance: kuaiche_web_status
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 10.64.4.156:9116

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'


#  - job_name: 'aspnetcore'
#  #    scrape_interval: 10s
#  #    static_configs:
#  #      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
